name: Build, release wasm

on:
  push:
    branches: [ main ]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout 
      uses: actions/checkout@v2

    - name: Install cargo-make
      uses: davidB/rust-cargo-make@v1

    - name: Run tests, lints
      run: cargo make verify
      working-directory: burraco-seed

    - name: Build release
      run: cargo make build_release
      working-directory: burraco-seed

    - uses: actions/upload-artifact@v2
      with:
        name: burraco.wasm
        path: ./burraco-seed/pkg/package_bg.wasm
